services:
  # === Backend FastAPI ===
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatbot
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - chatbot-net
    tmpfs:
      - /dev/shm:size=8G

  # === Frontend Next.js ===
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - chatbot-net

  # === Base de données PostgreSQL ===
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbot-net

  # === Redis (cache / sessions) ===
  redis:
    image: redis:7
    networks:
      - chatbot-net

networks:
  chatbot-net:

volumes:
  pgdata: